spring:
  application:
    name: rest-with-spring-boot-and-kotlin

  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
